# Generated by Django 3.0.5 on 2020-05-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='emailaddress',
            new_name='emailAddress',
        ),
    ]
